import { TokenClassConsts, postfixTokenClass } from '../../common/constants';
/**
 * Inspired by VS Code ColorTheme Default Light+.
 */

export const lightThemeData = {
    base: 'vs',
    inherit: true,
    rules: [
        { token: '', foreground: '1F1F26' },
        { token: postfixTokenClass(TokenClassConsts.BINARY), foreground: 'F25050' },
        { token: postfixTokenClass(TokenClassConsts.BINARY_ESCAPE), foreground: 'F25050' },
        { token: postfixTokenClass(TokenClassConsts.COMMENT), foreground: '9F9FA2' },
        { token: postfixTokenClass(TokenClassConsts.COMMENT_QUOTE), foreground: '9F9FA2' },
        { token: postfixTokenClass(TokenClassConsts.DELIMITER), foreground: '1F1F26' },
        { token: postfixTokenClass(TokenClassConsts.DELIMITER_CURLY), foreground: '1F1F26' },
        { token: postfixTokenClass(TokenClassConsts.DELIMITER_PAREN), foreground: '1F1F26' },
        { token: postfixTokenClass(TokenClassConsts.DELIMITER_PAREN_SQL), foreground: '1F1F26' },
        { token: postfixTokenClass(TokenClassConsts.DELIMITER_SQUARE), foreground: '1F1F26' },
        { token: postfixTokenClass(TokenClassConsts.IDENTIFIER), foreground: '1F1F26' },
        { token: postfixTokenClass(TokenClassConsts.IDENTIFIER_QUOTE), foreground: '1F1F26' },
        { token: postfixTokenClass(TokenClassConsts.KEYWORD), foreground: '0065FD' },
        { token: postfixTokenClass(TokenClassConsts.KEYWORD_SCOPE), foreground: '0065FD' },
        { token: postfixTokenClass(TokenClassConsts.NUMBER), foreground: 'F25050' },
        { token: postfixTokenClass(TokenClassConsts.NUMBER_FLOAT), foreground: 'F25050' },
        { token: postfixTokenClass(TokenClassConsts.NUMBER_BINARY), foreground: 'F25050' },
        { token: postfixTokenClass(TokenClassConsts.NUMBER_OCTAL), foreground: 'F25050' },
        { token: postfixTokenClass(TokenClassConsts.NUMBER_HEX), foreground: 'F25050' },
        { token: postfixTokenClass(TokenClassConsts.OPERATOR), foreground: '0065FD' },
        { token: postfixTokenClass(TokenClassConsts.OPERATOR_KEYWORD), foreground: '0065FD' },
        { token: postfixTokenClass(TokenClassConsts.OPERATOR_SYMBOL), foreground: '0065FD' },
        { token: postfixTokenClass(TokenClassConsts.PREDEFINED), foreground: '#00B42A' },
        { token: postfixTokenClass(TokenClassConsts.STRING), foreground: '#00B42A' },
        { token: postfixTokenClass(TokenClassConsts.STRING_ESCAPE), foreground: '#00B42A' },
        { token: postfixTokenClass(TokenClassConsts.TYPE), foreground: '1F1F26' },
        { token: postfixTokenClass(TokenClassConsts.VARIABLE), foreground: '00B42A' },
        { token: postfixTokenClass(TokenClassConsts.STRING_DOUBLE), foreground: '00B42A' },
    ],

    colors: {
        'editor.foreground': '#1F1F26',
        'editor.background': '#ffffff',
        'editor.selectionBackground': '#BED8FD',
        'editor.lineHighlightBackground': '#ffffff',
        'editorCursor.foreground': '#1F1F26',
        'editorWhitespace.foreground': '#E5F0FF',
        'editorIndentGuide.activeBackground': '#ff0000',
        'editor.selectionHighlightBorder': '#222218',
        'editorLineNumber.foreground': '#7F7F83',
        'editorSuggestWidget.highlightForeground': '#0065FD',
        'editorSuggestWidget.focusHighlightForeground': '#0065FD',
        'editorBracketHighlight.foreground1': '#1F1F26',
        'editorBracketHighlight.foreground2': '#1F1F26',
        'editorBracketHighlight.foreground3': '#1F1F26',
        'editorBracketHighlight.foreground4': '#1F1F26',
        'editorBracketHighlight.foreground5': '#1F1F26',
        'editorBracketHighlight.foreground6': '#1F1F26',
    },
};
