// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/(app)/[organization]/@workspaceDrawer/(.)agent-runs/[workId]/workspace/[connectionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/agent-runs/[workId]/workspace/[connectionId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/@workspaceDrawer/(.)agent-runs/[workId]/workspace/[connectionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/[connectionId]/chatbot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/[connectionId]/chatbot">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/[connectionId]/chatbot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/[connectionId]/explorer/[[...slug]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/[connectionId]/explorer/[[...slug]]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/[connectionId]/explorer/[[...slug]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/[connectionId]/monitoring/error-queries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/[connectionId]/monitoring/error-queries">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/[connectionId]/monitoring/error-queries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/[connectionId]/monitoring/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/[connectionId]/monitoring/logs">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/[connectionId]/monitoring/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/[connectionId]/monitoring/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/[connectionId]/monitoring/overview">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/[connectionId]/monitoring/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/[connectionId]/monitoring/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/[connectionId]/monitoring">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/[connectionId]/monitoring/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/[connectionId]/monitoring/slow-queries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/[connectionId]/monitoring/slow-queries">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/[connectionId]/monitoring/slow-queries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/[connectionId]/privileges/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/[connectionId]/privileges">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/[connectionId]/privileges/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/[connectionId]/privileges/role/[name]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/[connectionId]/privileges/role/[name]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/[connectionId]/privileges/role/[name]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/[connectionId]/privileges/user/[name]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/[connectionId]/privileges/user/[name]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/[connectionId]/privileges/user/[name]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/[connectionId]/sql-console/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/[connectionId]/sql-console">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/[connectionId]/sql-console/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/agent-runs/[workId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/agent-runs/[workId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/agent-runs/[workId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/agent-runs/[workId]/workspace/[connectionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/agent-runs/[workId]/workspace/[connectionId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/agent-runs/[workId]/workspace/[connectionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/agent-runs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/agent-runs">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/agent-runs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/ai-usage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/ai-usage">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/ai-usage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/comparisons/[comparisonId]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/comparisons/[comparisonId]/edit">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/comparisons/[comparisonId]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/comparisons/[comparisonId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/comparisons/[comparisonId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/comparisons/[comparisonId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/comparisons/[comparisonId]/runs/[runId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/comparisons/[comparisonId]/runs/[runId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/comparisons/[comparisonId]/runs/[runId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/comparisons/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/comparisons/new">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/comparisons/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/comparisons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/comparisons">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/comparisons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/connections/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/connections">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/connections/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/query-audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/query-audit">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/query-audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/settings/ai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/settings/ai">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/settings/ai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/settings/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/settings/billing">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/settings/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/settings/invitations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/settings/invitations">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/settings/invitations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/settings/members/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/settings/members">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/settings/members/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/settings/organization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/settings/organization">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/settings/organization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/settings">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/settings/query-audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/settings/query-audit">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/settings/query-audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/snake/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[organization]/snake">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/snake/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/charts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/charts">> = Specific
  const handler = {} as typeof import("../../../app/(app)/charts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(app)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/sign-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-in">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/sign-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/sign-up/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-up">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/sign-up/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/create-organization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/create-organization">> = Specific
  const handler = {} as typeof import("../../../app/create-organization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/embed/hacker-news/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/embed/hacker-news">> = Specific
  const handler = {} as typeof import("../../../app/embed/hacker-news/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/mcp/authorize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mcp/authorize">> = Specific
  const handler = {} as typeof import("../../../app/mcp/authorize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/organization/accept-invitation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organization/accept-invitation">> = Specific
  const handler = {} as typeof import("../../../app/organization/accept-invitation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/welcome/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/welcome">> = Specific
  const handler = {} as typeof import("../../../app/welcome/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/actions/execute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/actions/execute">> = Specific
  const handler = {} as typeof import("../../../app/api/actions/execute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ai/model/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/model/generate">> = Specific
  const handler = {} as typeof import("../../../app/api/ai/model/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ai/model/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/model/stream">> = Specific
  const handler = {} as typeof import("../../../app/api/ai/model/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ai/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/stream">> = Specific
  const handler = {} as typeof import("../../../app/api/ai/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ai/usage/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/usage/events">> = Specific
  const handler = {} as typeof import("../../../app/api/ai/usage/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ai/usage/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/usage/overview">> = Specific
  const handler = {} as typeof import("../../../app/api/ai/usage/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/[...all]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...all]">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/[...all]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/anonymous/bootstrap/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/anonymous/bootstrap">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/anonymous/bootstrap/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/anonymous/recover/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/anonymous/recover">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/anonymous/recover/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/demo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/demo">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/demo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/request-password-reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/request-password-reset">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/request-password-reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/resend-verification/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/resend-verification">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/resend-verification/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../../app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/chat/session/[sessionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/session/[sessionId]">> = Specific
  const handler = {} as typeof import("../../../app/api/chat/session/[sessionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/chat/session/copilot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/session/copilot">> = Specific
  const handler = {} as typeof import("../../../app/api/chat/session/copilot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/chat/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/sessions">> = Specific
  const handler = {} as typeof import("../../../app/api/chat/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/copilot/action/inline-ask/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/copilot/action/inline-ask">> = Specific
  const handler = {} as typeof import("../../../app/api/copilot/action/inline-ask/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/copilot/action/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/copilot/action">> = Specific
  const handler = {} as typeof import("../../../app/api/copilot/action/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cron/embed-demo-cleanup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/embed-demo-cleanup">> = Specific
  const handler = {} as typeof import("../../../app/api/cron/embed-demo-cleanup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/electron/auth/bridge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/electron/auth/bridge">> = Specific
  const handler = {} as typeof import("../../../app/api/electron/auth/bridge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/electron/auth/consume/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/electron/auth/consume">> = Specific
  const handler = {} as typeof import("../../../app/api/electron/auth/consume/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/electron/auth/finalize-email-verification/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/electron/auth/finalize-email-verification">> = Specific
  const handler = {} as typeof import("../../../app/api/electron/auth/finalize-email-verification/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/electron/auth/finalize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/electron/auth/finalize">> = Specific
  const handler = {} as typeof import("../../../app/api/electron/auth/finalize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/electron/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/electron/auth/session">> = Specific
  const handler = {} as typeof import("../../../app/api/electron/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/electron/auth/sign-in/email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/electron/auth/sign-in/email">> = Specific
  const handler = {} as typeof import("../../../app/api/electron/auth/sign-in/email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/electron/auth/start/github/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/electron/auth/start/github">> = Specific
  const handler = {} as typeof import("../../../app/api/electron/auth/start/github/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/electron/auth/start/google/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/electron/auth/start/google">> = Specific
  const handler = {} as typeof import("../../../app/api/electron/auth/start/google/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/embed-demo/bootstrap/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/embed-demo/bootstrap">> = Specific
  const handler = {} as typeof import("../../../app/api/embed-demo/bootstrap/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/local-files/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/local-files/create">> = Specific
  const handler = {} as typeof import("../../../app/api/local-files/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/local-files/inspect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/local-files/inspect">> = Specific
  const handler = {} as typeof import("../../../app/api/local-files/inspect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/local-files/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/local-files/refresh">> = Specific
  const handler = {} as typeof import("../../../app/api/local-files/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/local-files/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/local-files">> = Specific
  const handler = {} as typeof import("../../../app/api/local-files/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mcp/desktop-grant/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/desktop-grant/refresh">> = Specific
  const handler = {} as typeof import("../../../app/api/mcp/desktop-grant/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mcp/desktop-grant/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/desktop-grant">> = Specific
  const handler = {} as typeof import("../../../app/api/mcp/desktop-grant/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mcp/link/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/link/approve">> = Specific
  const handler = {} as typeof import("../../../app/api/mcp/link/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mcp/link/deny/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/link/deny">> = Specific
  const handler = {} as typeof import("../../../app/api/mcp/link/deny/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mcp/link/poll/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/link/poll">> = Specific
  const handler = {} as typeof import("../../../app/api/mcp/link/poll/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mcp/link/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/link/start">> = Specific
  const handler = {} as typeof import("../../../app/api/mcp/link/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mcp/local-ai/bridges/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/local-ai/bridges/register">> = Specific
  const handler = {} as typeof import("../../../app/api/mcp/local-ai/bridges/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mcp/local-ai/jobs/[jobId]/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/local-ai/jobs/[jobId]/complete">> = Specific
  const handler = {} as typeof import("../../../app/api/mcp/local-ai/jobs/[jobId]/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mcp/local-ai/jobs/claim/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/local-ai/jobs/claim">> = Specific
  const handler = {} as typeof import("../../../app/api/mcp/local-ai/jobs/claim/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mcp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp">> = Specific
  const handler = {} as typeof import("../../../app/api/mcp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mcp/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/settings">> = Specific
  const handler = {} as typeof import("../../../app/api/mcp/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mcp/tokens/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/tokens/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/mcp/tokens/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mcp/tokens/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp/tokens">> = Specific
  const handler = {} as typeof import("../../../app/api/mcp/tokens/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/monitoring/error-queries/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/error-queries">> = Specific
  const handler = {} as typeof import("../../../app/api/monitoring/error-queries/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/monitoring/query-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/query-logs">> = Specific
  const handler = {} as typeof import("../../../app/api/monitoring/query-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/monitoring/recent-queries/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/recent-queries">> = Specific
  const handler = {} as typeof import("../../../app/api/monitoring/recent-queries/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/monitoring/slow-queries/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/slow-queries">> = Specific
  const handler = {} as typeof import("../../../app/api/monitoring/slow-queries/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/monitoring/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/summary">> = Specific
  const handler = {} as typeof import("../../../app/api/monitoring/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/monitoring/timeline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/timeline">> = Specific
  const handler = {} as typeof import("../../../app/api/monitoring/timeline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/organization/access/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organization/access">> = Specific
  const handler = {} as typeof import("../../../app/api/organization/access/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/organization/ai-providers/[providerId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organization/ai-providers/[providerId]">> = Specific
  const handler = {} as typeof import("../../../app/api/organization/ai-providers/[providerId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/organization/ai-providers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organization/ai-providers">> = Specific
  const handler = {} as typeof import("../../../app/api/organization/ai-providers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/organization/ai-providers/system-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organization/ai-providers/system-status">> = Specific
  const handler = {} as typeof import("../../../app/api/organization/ai-providers/system-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/organization/ai-providers/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organization/ai-providers/test">> = Specific
  const handler = {} as typeof import("../../../app/api/organization/ai-providers/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/organization/billing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organization/billing">> = Specific
  const handler = {} as typeof import("../../../app/api/organization/billing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/organization/result-set-retention/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organization/result-set-retention">> = Specific
  const handler = {} as typeof import("../../../app/api/organization/result-set-retention/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/organization/result-set-storage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organization/result-set-storage">> = Specific
  const handler = {} as typeof import("../../../app/api/organization/result-set-storage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/organizations/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organizations/create">> = Specific
  const handler = {} as typeof import("../../../app/api/organizations/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/privileges/clusters/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/privileges/clusters">> = Specific
  const handler = {} as typeof import("../../../app/api/privileges/clusters/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/privileges/roles/[name]/global/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/privileges/roles/[name]/global">> = Specific
  const handler = {} as typeof import("../../../app/api/privileges/roles/[name]/global/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/privileges/roles/[name]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/privileges/roles/[name]">> = Specific
  const handler = {} as typeof import("../../../app/api/privileges/roles/[name]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/privileges/roles/[name]/scoped/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/privileges/roles/[name]/scoped">> = Specific
  const handler = {} as typeof import("../../../app/api/privileges/roles/[name]/scoped/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/privileges/roles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/privileges/roles">> = Specific
  const handler = {} as typeof import("../../../app/api/privileges/roles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/privileges/targets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/privileges/targets">> = Specific
  const handler = {} as typeof import("../../../app/api/privileges/targets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/privileges/users/[name]/global/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/privileges/users/[name]/global">> = Specific
  const handler = {} as typeof import("../../../app/api/privileges/users/[name]/global/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/privileges/users/[name]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/privileges/users/[name]">> = Specific
  const handler = {} as typeof import("../../../app/api/privileges/users/[name]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/privileges/users/[name]/scoped/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/privileges/users/[name]/scoped">> = Specific
  const handler = {} as typeof import("../../../app/api/privileges/users/[name]/scoped/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/privileges/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/privileges/users">> = Specific
  const handler = {} as typeof import("../../../app/api/privileges/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/result-set-exports/[exportId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/result-set-exports/[exportId]">> = Specific
  const handler = {} as typeof import("../../../app/api/result-set-exports/[exportId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/result-sets/cleanup-expired/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/result-sets/cleanup-expired">> = Specific
  const handler = {} as typeof import("../../../app/api/result-sets/cleanup-expired/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/result-sets/cleanup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/result-sets/cleanup">> = Specific
  const handler = {} as typeof import("../../../app/api/result-sets/cleanup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/runtime/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runtime/[...path]">> = Specific
  const handler = {} as typeof import("../../../app/api/runtime/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sql-console/query/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sql-console/query/stream">> = Specific
  const handler = {} as typeof import("../../../app/api/sql-console/query/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/works/[workId]/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/works/[workId]/events">> = Specific
  const handler = {} as typeof import("../../../app/api/works/[workId]/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/works/[workId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/works/[workId]">> = Specific
  const handler = {} as typeof import("../../../app/api/works/[workId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/works/[workId]/snapshot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/works/[workId]/snapshot">> = Specific
  const handler = {} as typeof import("../../../app/api/works/[workId]/snapshot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/workspace/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspace/export">> = Specific
  const handler = {} as typeof import("../../../app/api/workspace/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/workspace/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspace/import">> = Specific
  const handler = {} as typeof import("../../../app/api/workspace/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/(admin)/audit/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/audit">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/audit/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/[connectionId]/explorer/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[organization]/[connectionId]/explorer">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/[connectionId]/explorer/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/[connectionId]/monitoring/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[organization]/[connectionId]/monitoring">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/[connectionId]/monitoring/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/[connectionId]/sql-console/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[organization]/[connectionId]/sql-console">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/[connectionId]/sql-console/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[organization]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/[organization]/settings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[organization]/settings">> = Specific
  const handler = {} as typeof import("../../../app/(app)/[organization]/settings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
